version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: icalendar
      POSTGRES_USER: icaluser
      POSTGRES_PASSWORD: icalpass
    ports:
      - "5436:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/icalendar
      SPRING_DATASOURCE_USERNAME: icaluser
      SPRING_DATASOURCE_PASSWORD: icalpass
